packages:
  - packages/*
  - examples/*
  - test-e2e/site
  - docs

catalog:
  '@rust-gear/glob': 1.0.0
  '@swc/core': 1.15.33
  next: ^16.2.6
  postcss: 8.5.14
  react: ^19.2.6
  react-dom: ^19.2.6
  webpack: 5.106.2
  zss-engine: 2.2.8

onlyBuiltDependencies:
  - '@swc/core'
