packages:
  - packages/*
  - examples/*
  - test-e2e/site
  - docs

catalog:
  '@swc/core': 1.15.8
  next: ^16.1.1
  react: ^19.2.1
  react-dom: ^19.2.1
  webpack: 5.101.0
  zss-engine: 2.2.0
  postcss: 8.5.6

onlyBuiltDependencies:
  - '@swc/core'
