packages:
  - packages/*
  - examples/*
  - test-e2e/site
  - docs

catalog:
  '@swc/core': 1.15.2
  'zss-engine': 2.1.2
  'webpack': 5.101.0
  'next': 16.0.10
  'react': 19.2.1
  'react-dom': 19.2.1
