name: Setup test environment
description: Sets unpublish files for testing

runs:
  using: composite
  steps:
    - name: Cleanup
      shell: bash
      run: |
        pnpm rm test-e2e/site/node_modules/@plumeria/core/*
        pnpm rm test-e2e/site/node_modules/@plumeria/collection/*
        pnpm rm test-e2e/site/node_modules/@plumeria/next/*
        pnpm rm test-e2e/site/node_modules/@plumeria/compiler/*

    - name: Copy test-env
      shell: bash
      run: |
        pnpm cp packages/core/* test-e2e/site/node_modules/@plumeria/core/
        pnpm cp packages/collection/* test-e2e/site/node_modules/@plumeria/collection/
        pnpm cp packages/next/* test-e2e/site/node_modules/@plumeria/next/
        pnpm cp packages/compiler/* test-e2e/site/node_modules/@plumeria/compiler/
