name: Setup test environment
description: Sets unpublish files for testing

runs:
  using: composite
  steps:
    - name: Cleanup
      shell: bash
      run: |
        pnpm shx rm -rf test-e2e/site/node_modules/@plumeria/core/*
        pnpm shx rm -rf test-e2e/site/node_modules/@plumeria/collection/*
        pnpm shx rm -rf test-e2e/site/node_modules/@plumeria/next/*
        pnpm shx rm -rf test-e2e/site/node_modules/@plumeria/compiler/*

    - name: Copy test-env
      shell: bash
      run: |
        pnpm shx cp -r packages/core/* test-e2e/site/node_modules/@plumeria/core/
        pnpm shx cp -r packages/collection/* test-e2e/site/node_modules/@plumeria/collection/
        pnpm shx cp -r packages/next/* test-e2e/site/node_modules/@plumeria/next/
        pnpm shx cp -r packages/compiler/* test-e2e/site/node_modules/@plumeria/compiler/
