name: Setup Verification Files
description: Sets up verification files for testing

runs:
  using: composite
  steps:
    - name: Setting verification files
      shell: bash
      run: |
        rm -rf test-e2e/site/node_modules/@plumeria/collection/*
        rm -rf test-e2e/site/node_modules/@plumeria/compiler/*
        rm -rf test-e2e/site/node_modules/@plumeria/core/*
        rm -rf test-e2e/site/node_modules/@plumeria/next/*
        cp -r packages/core/* test-e2e/site/node_modules/@plumeria/core/
        cp -r packages/collection/* test-e2e/site/node_modules/@plumeria/collection/
        cp -r packages/next/* test-e2e/site/node_modules/@plumeria/next/
        cp -r packages/compiler/* test-e2e/site/node_modules/@plumeria/compiler/
