name: Setup test environment
description: Sets unpublish files for testing

runs:
  using: composite
  steps:
    - name: Cleanup
      shell: bash
      run: |
        pnpm rimraf test-e2e/site/node_modules/@plumeria/core/*
        pnpm rimraf test-e2e/site/node_modules/@plumeria/collection/*
        pnpm rimraf test-e2e/site/node_modules/@plumeria/next/*
        pnpm rimraf test-e2e/site/node_modules/@plumeria/compiler/*

    - name: Copy test-env
      shell: bash
      run: |
        pnpm cpy "packages/core/**" "test-e2e/site/node_modules/@plumeria/core"
        pnpm cpy "packages/collection/**" "test-e2e/site/node_modules/@plumeria/collection"
        pnpm cpy "packages/next/**" "test-e2e/site/node_modules/@plumeria/next"
        pnpm cpy "packages/compiler/**" "test-e2e/site/node_modules/@plumeria/compiler"
