import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { planRelease } from '../src/release';
import { resetTsconfigCache, resolveSourcePath } from '../src/resolve';

const add = (dir: string, name: string, content: string) => {
  const file = path.join(dir, name);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, 'utf8');
  return file;
};

const THEME = `import { css } from '@plumeria/core';

export const theme = css.createTheme('.dark', {
  primary: { default: 'red', theme: 'blue' },
});
`;

const consumer = (specifier: string) => `import { css } from '@plumeria/core';
import { theme } from '${specifier}';

export const styles = css.create({
  card: { color: theme.primary },
});
`;

const ALIASED = JSON.stringify({
  compilerOptions: { paths: { '@/*': ['./src/*'] } },
});

describe('import resolution', () => {
  let dir: string;
  let cwd: string;

  beforeEach(() => {
    dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'resolve-')));
    cwd = process.cwd();
    process.chdir(dir);
    resetTsconfigCache();
  });

  afterEach(() => {
    process.chdir(cwd);
    fs.rmSync(dir, { recursive: true, force: true });
    resetTsconfigCache();
  });

  describe('resolveSourcePath', () => {
    it('leaves the core import alone', () => {
      const importer = add(dir, 'src/a.ts', '');
      expect(resolveSourcePath('@plumeria/core', importer)).toBeNull();
    });

    it('keeps a dot in the filename out of the extension', () => {
      const importer = add(dir, 'src/Card.tsx', '');
      const target = add(dir, 'src/Card.theme.ts', '');
      expect(resolveSourcePath('./Card.theme', importer)).toBe(target);
    });

    it('resolves a directory through its index file', () => {
      const importer = add(dir, 'src/Card.tsx', '');
      const target = add(dir, 'src/theme/index.ts', '');
      expect(resolveSourcePath('./theme', importer)).toBe(target);
    });

    it('resolves a tsconfig paths alias', () => {
      add(dir, 'tsconfig.json', ALIASED);
      const importer = add(dir, 'src/Card.tsx', '');
      const target = add(dir, 'src/theme.ts', '');
      expect(resolveSourcePath('@/theme', importer)).toBe(target);
    });

    it('reads a .js specifier as the TypeScript file beside it', () => {
      const importer = add(dir, 'src/Card.tsx', '');
      const target = add(dir, 'src/theme.ts', '');
      expect(resolveSourcePath('./theme.js', importer)).toBe(target);
    });

    it('returns nothing when a rewritten extension names no file either', () => {
      const importer = add(dir, 'src/Card.tsx', '');
      expect(resolveSourcePath('./missing.js', importer)).toBeNull();
    });

    it('returns nothing when an alias names no file', () => {
      add(dir, 'tsconfig.json', ALIASED);
      const importer = add(dir, 'src/Card.tsx', '');
      expect(resolveSourcePath('@/missing', importer)).toBeNull();
    });

    it('reads a tsconfig that carries comments', () => {
      add(
        dir,
        'tsconfig.json',
        '{\n  // generated by create-next-app\n  "compilerOptions": { "paths": { "@/*": ["./src/*"] } }\n}\n',
      );
      const importer = add(dir, 'src/Card.tsx', '');
      const target = add(dir, 'src/theme.ts', '');
      expect(resolveSourcePath('@/theme', importer)).toBe(target);
    });

    it('follows an extends chain to the paths it declares', () => {
      add(dir, 'base.json', ALIASED);
      add(dir, 'tsconfig.json', JSON.stringify({ extends: './base.json' }));
      const importer = add(dir, 'src/Card.tsx', '');
      const target = add(dir, 'src/theme.ts', '');
      expect(resolveSourcePath('@/theme', importer)).toBe(target);
    });

    it('maps a .js specifier onto the TypeScript source', () => {
      const importer = add(dir, 'src/Card.tsx', '');
      const target = add(dir, 'src/theme.ts', '');
      expect(resolveSourcePath('./theme.js', importer)).toBe(target);
    });

    it('returns null for a bare specifier with no alias', () => {
      const importer = add(dir, 'src/Card.tsx', '');
      expect(resolveSourcePath('react', importer)).toBeNull();
    });

    it('returns null when nothing is there', () => {
      const importer = add(dir, 'src/Card.tsx', '');
      expect(resolveSourcePath('./missing', importer)).toBeNull();
    });
  });

  describe('planRelease resolves theme imports', () => {
    const css = (extra: () => void, specifier: string) => {
      extra();
      add(dir, 'src/Card.tsx', consumer(specifier));
      return planRelease([dir]).stylesheets[0];
    };

    it('through a plain relative import', () => {
      const sheet = css(() => add(dir, 'src/theme.ts', THEME), './theme');
      expect(sheet.reports).toEqual([]);
      expect(sheet.css).toContain('color: var(--');
    });

    it('through a dotted filename', () => {
      const sheet = css(
        () => add(dir, 'src/Card.theme.ts', THEME),
        './Card.theme',
      );
      expect(sheet.reports).toEqual([]);
      expect(sheet.css).toContain('color: var(--');
    });

    it('through a directory index', () => {
      const sheet = css(() => add(dir, 'src/theme/index.ts', THEME), './theme');
      expect(sheet.reports).toEqual([]);
      expect(sheet.css).toContain('color: var(--');
    });

    it('through a tsconfig paths alias', () => {
      const sheet = css(() => {
        add(dir, 'tsconfig.json', ALIASED);
        add(dir, 'src/theme.ts', THEME);
      }, '@/theme');
      expect(sheet.reports).toEqual([]);
      expect(sheet.css).toContain('color: var(--');
    });
  });
});
