pub static DIRECT_LONGHANDS: &[(&str, &[&str])] = &[
    (
        "margin",
        &[
            "margin-top",
            "margin-bottom",
            "margin-left",
            "margin-right",
            "margin-block",
            "margin-inline",
        ],
    ),
    (
        "margin-block",
        &[
            "margin-block-start",
            "margin-block-end",
            "margin-top",
            "margin-bottom",
        ],
    ),
    (
        "margin-inline",
        &[
            "margin-inline-start",
            "margin-inline-end",
            "margin-left",
            "margin-right",
        ],
    ),
    (
        "padding",
        &[
            "padding-top",
            "padding-bottom",
            "padding-left",
            "padding-right",
            "padding-block",
            "padding-inline",
        ],
    ),
    (
        "padding-block",
        &[
            "padding-block-start",
            "padding-block-end",
            "padding-top",
            "padding-bottom",
        ],
    ),
    (
        "padding-inline",
        &[
            "padding-inline-start",
            "padding-inline-end",
            "padding-left",
            "padding-right",
        ],
    ),
    (
        "inset",
        &[
            "top",
            "bottom",
            "left",
            "right",
            "inset-block",
            "inset-inline",
        ],
    ),
    (
        "inset-block",
        &["inset-block-start", "inset-block-end", "top", "bottom"],
    ),
    (
        "inset-inline",
        &["inset-inline-start", "inset-inline-end", "left", "right"],
    ),
    (
        "background",
        &[
            "background-image",
            "background-size",
            "background-position",
            "background-repeat",
            "background-origin",
            "background-clip",
            "background-attachment",
            "background-color",
        ],
    ),
    (
        "background-position",
        &["background-position-x", "background-position-y"],
    ),
    (
        "font",
        &[
            "font-style",
            "font-variant",
            "font-weight",
            "font-stretch",
            "font-size",
            "font-family",
            "line-height",
        ],
    ),
    (
        "font-variant",
        &[
            "font-variant-caps",
            "font-variant-numeric",
            "font-variant-ligatures",
            "font-variant-east-asian",
            "font-variant-alternates",
            "font-variant-position",
            "font-variant-emoji",
        ],
    ),
    (
        "font-synthesis",
        &[
            "font-synthesis-weight",
            "font-synthesis-style",
            "font-synthesis-small-caps",
        ],
    ),
    (
        "border",
        &[
            "border-width",
            "border-style",
            "border-color",
            "border-top",
            "border-bottom",
            "border-left",
            "border-right",
            "border-block",
            "border-inline",
        ],
    ),
    (
        "border-top",
        &["border-top-width", "border-top-style", "border-top-color"],
    ),
    (
        "border-bottom",
        &[
            "border-bottom-width",
            "border-bottom-style",
            "border-bottom-color",
        ],
    ),
    (
        "border-left",
        &[
            "border-left-width",
            "border-left-style",
            "border-left-color",
        ],
    ),
    (
        "border-right",
        &[
            "border-right-width",
            "border-right-style",
            "border-right-color",
        ],
    ),
    (
        "border-width",
        &[
            "border-top-width",
            "border-bottom-width",
            "border-left-width",
            "border-right-width",
            "border-block-width",
            "border-inline-width",
        ],
    ),
    (
        "border-style",
        &[
            "border-top-style",
            "border-bottom-style",
            "border-left-style",
            "border-right-style",
            "border-block-style",
            "border-inline-style",
        ],
    ),
    (
        "border-color",
        &[
            "border-top-color",
            "border-bottom-color",
            "border-left-color",
            "border-right-color",
            "border-block-color",
            "border-inline-color",
        ],
    ),
    (
        "list-style",
        &["list-style-type", "list-style-position", "list-style-image"],
    ),
    (
        "border-radius",
        &[
            "border-top-right-radius",
            "border-top-left-radius",
            "border-bottom-right-radius",
            "border-bottom-left-radius",
            "border-start-start-radius",
            "border-start-end-radius",
            "border-end-start-radius",
            "border-end-end-radius",
        ],
    ),
    (
        "corner-shape",
        &[
            "corner-top-right-shape",
            "corner-top-left-shape",
            "corner-bottom-right-shape",
            "corner-bottom-left-shape",
            "corner-start-start-shape",
            "corner-start-end-shape",
            "corner-end-start-shape",
            "corner-end-end-shape",
        ],
    ),
    (
        "transition",
        &[
            "transition-delay",
            "transition-duration",
            "transition-property",
            "transition-timing-function",
            "transition-behavior",
        ],
    ),
    (
        "animation",
        &[
            "animation-name",
            "animation-duration",
            "animation-timing-function",
            "animation-delay",
            "animation-iteration-count",
            "animation-direction",
            "animation-fill-mode",
            "animation-play-state",
            "animation-timeline",
            "animation-range",
        ],
    ),
    (
        "animation-range",
        &["animation-range-start", "animation-range-end"],
    ),
    (
        "border-block",
        &[
            "border-block-start",
            "border-block-end",
            "border-block-width",
            "border-block-style",
            "border-block-color",
            "border-top",
            "border-bottom",
        ],
    ),
    (
        "border-block-end",
        &[
            "border-block-end-width",
            "border-block-end-style",
            "border-block-end-color",
        ],
    ),
    (
        "border-block-start",
        &[
            "border-block-start-width",
            "border-block-start-style",
            "border-block-start-color",
        ],
    ),
    (
        "border-block-width",
        &[
            "border-block-start-width",
            "border-block-end-width",
            "border-top-width",
            "border-bottom-width",
        ],
    ),
    (
        "border-block-style",
        &[
            "border-block-start-style",
            "border-block-end-style",
            "border-top-style",
            "border-bottom-style",
        ],
    ),
    (
        "border-block-color",
        &[
            "border-block-start-color",
            "border-block-end-color",
            "border-top-color",
            "border-bottom-color",
        ],
    ),
    (
        "border-image",
        &[
            "border-image-source",
            "border-image-slice",
            "border-image-width",
            "border-image-outset",
            "border-image-repeat",
        ],
    ),
    (
        "border-inline",
        &[
            "border-inline-start",
            "border-inline-end",
            "border-inline-width",
            "border-inline-style",
            "border-inline-color",
            "border-left",
            "border-right",
        ],
    ),
    (
        "border-inline-end",
        &[
            "border-inline-end-width",
            "border-inline-end-style",
            "border-inline-end-color",
        ],
    ),
    (
        "border-inline-start",
        &[
            "border-inline-start-width",
            "border-inline-start-style",
            "border-inline-start-color",
        ],
    ),
    (
        "border-inline-width",
        &[
            "border-inline-start-width",
            "border-inline-end-width",
            "border-left-width",
            "border-right-width",
        ],
    ),
    (
        "border-inline-style",
        &[
            "border-inline-start-style",
            "border-inline-end-style",
            "border-left-style",
            "border-right-style",
        ],
    ),
    (
        "border-inline-color",
        &[
            "border-inline-start-color",
            "border-inline-end-color",
            "border-left-color",
            "border-right-color",
        ],
    ),
    (
        "column-rule",
        &[
            "column-rule-width",
            "column-rule-style",
            "column-rule-color",
        ],
    ),
    ("columns", &["column-width", "column-count"]),
    ("flex", &["flex-grow", "flex-shrink", "flex-basis"]),
    ("flex-flow", &["flex-direction", "flex-wrap"]),
    (
        "grid",
        &[
            "grid-template",
            "grid-auto-rows",
            "grid-auto-columns",
            "grid-auto-flow",
            "grid-gap",
            "gap",
        ],
    ),
    (
        "grid-template",
        &[
            "grid-template-columns",
            "grid-template-rows",
            "grid-template-areas",
        ],
    ),
    ("grid-area", &["grid-row", "grid-column"]),
    ("grid-column", &["grid-column-start", "grid-column-end"]),
    ("grid-gap", &["grid-row-gap", "grid-column-gap"]),
    ("grid-row", &["grid-row-start", "grid-row-end"]),
    ("gap", &["row-gap", "column-gap"]),
    ("place-items", &["align-items", "justify-items"]),
    ("place-content", &["align-content", "justify-content"]),
    ("place-self", &["align-self", "justify-self"]),
    (
        "overflow",
        &[
            "overflow-x",
            "overflow-y",
            "overflow-block",
            "overflow-inline",
        ],
    ),
    (
        "overscroll-behavior",
        &[
            "overscroll-behavior-x",
            "overscroll-behavior-y",
            "overscroll-behavior-block",
            "overscroll-behavior-inline",
        ],
    ),
    (
        "scroll-margin",
        &[
            "scroll-margin-top",
            "scroll-margin-bottom",
            "scroll-margin-left",
            "scroll-margin-right",
            "scroll-margin-block",
            "scroll-margin-inline",
        ],
    ),
    (
        "scroll-margin-block",
        &[
            "scroll-margin-block-start",
            "scroll-margin-block-end",
            "scroll-margin-top",
            "scroll-margin-bottom",
        ],
    ),
    (
        "scroll-margin-inline",
        &[
            "scroll-margin-inline-start",
            "scroll-margin-inline-end",
            "scroll-margin-left",
            "scroll-margin-right",
        ],
    ),
    (
        "scroll-padding",
        &[
            "scroll-padding-top",
            "scroll-padding-bottom",
            "scroll-padding-left",
            "scroll-padding-right",
            "scroll-padding-block",
            "scroll-padding-inline",
        ],
    ),
    (
        "scroll-padding-block",
        &[
            "scroll-padding-block-start",
            "scroll-padding-block-end",
            "scroll-padding-top",
            "scroll-padding-bottom",
        ],
    ),
    (
        "scroll-padding-inline",
        &[
            "scroll-padding-inline-start",
            "scroll-padding-inline-end",
            "scroll-padding-left",
            "scroll-padding-right",
        ],
    ),
    (
        "scroll-timeline",
        &["scroll-timeline-name", "scroll-timeline-axis"],
    ),
    (
        "view-timeline",
        &[
            "view-timeline-name",
            "view-timeline-axis",
            "view-timeline-inset",
        ],
    ),
    ("container", &["container-name", "container-type"]),
    (
        "contain-intrinsic-size",
        &[
            "contain-intrinsic-width",
            "contain-intrinsic-height",
            "contain-intrinsic-block-size",
            "contain-intrinsic-inline-size",
        ],
    ),
    (
        "position-try",
        &["position-try-fallbacks", "position-try-options"],
    ),
    ("marker", &["marker-start", "marker-mid", "marker-end"]),
    ("cue", &["cue-before", "cue-after"]),
    ("pause", &["pause-before", "pause-after"]),
    ("rest", &["rest-before", "rest-after"]),
    (
        "outline",
        &["outline-color", "outline-style", "outline-width"],
    ),
    (
        "text-decoration",
        &[
            "text-decoration-color",
            "text-decoration-style",
            "text-decoration-line",
            "text-decoration-thickness",
        ],
    ),
    (
        "text-emphasis",
        &["text-emphasis-style", "text-emphasis-color"],
    ),
    ("white-space", &["white-space-collapse", "white-space-trim"]),
    ("text-wrap", &["text-wrap-mode", "text-wrap-style"]),
    (
        "offset",
        &[
            "offset-position",
            "offset-path",
            "offset-distance",
            "offset-rotate",
            "offset-anchor",
        ],
    ),
    ("caret", &["caret-color", "caret-shape"]),
    (
        "mask",
        &[
            "mask-image",
            "mask-mode",
            "mask-position",
            "mask-size",
            "mask-repeat",
            "mask-origin",
            "mask-clip",
            "mask-composite",
        ],
    ),
    (
        "mask-border",
        &[
            "mask-border-source",
            "mask-border-slice",
            "mask-border-width",
            "mask-border-outset",
            "mask-border-repeat",
            "mask-border-mode",
        ],
    ),
];

pub static HEX_TO_COLOR_NAME: &[(&str, &str)] = &[
    ("#fff", "white"),
    ("#ffffff", "white"),
    ("#000", "black"),
    ("#000000", "black"),
    ("#f00", "red"),
    ("#ff0000", "red"),
    ("#dc143c", "crimson"),
    ("#b22222", "firebrick"),
    ("#8b0000", "darkred"),
    ("#cd5c5c", "indianred"),
    ("#0f0", "lime"),
    ("#00ff00", "lime"),
    ("#00f", "blue"),
    ("#0000ff", "blue"),
    ("#000080", "navy"),
    ("#00008b", "darkblue"),
    ("#0000cd", "mediumblue"),
    ("#191970", "midnightblue"),
    ("#4169e1", "royalblue"),
    ("#1e90ff", "dodgerblue"),
    ("#6495ed", "cornflowerblue"),
    ("#4682b4", "steelblue"),
    ("#5f9ea0", "cadetblue"),
    ("#87ceeb", "skyblue"),
    ("#87cefa", "lightskyblue"),
    ("#add8e6", "lightblue"),
    ("#b0e0e6", "powderblue"),
    ("#b0c4de", "lightsteelblue"),
    ("#e6e6fa", "lavender"),
    ("#ff0", "yellow"),
    ("#ffff00", "yellow"),
    ("#ffd700", "gold"),
    ("#daa520", "goldenrod"),
    ("#b8860b", "darkgoldenrod"),
    ("#eee8aa", "palegoldenrod"),
    ("#fafad2", "lightgoldenrodyellow"),
    ("#ffffe0", "lightyellow"),
    ("#fffacd", "lemonchiffon"),
    ("#f5deb3", "wheat"),
    ("#ffe4b5", "moccasin"),
    ("#ffdead", "navajowhite"),
    ("#f0e68c", "khaki"),
    ("#bdb76b", "darkkhaki"),
    ("#0ff", "aqua"),
    ("#00ffff", "aqua"),
    ("#008b8b", "darkcyan"),
    ("#20b2aa", "lightseagreen"),
    ("#40e0d0", "turquoise"),
    ("#48d1cc", "mediumturquoise"),
    ("#00ced1", "darkturquoise"),
    ("#afeeee", "paleturquoise"),
    ("#e0ffff", "lightcyan"),
    ("#f0ffff", "azure"),
    ("#f0f", "fuchsia"),
    ("#ff00ff", "fuchsia"),
    ("#8b008b", "darkmagenta"),
    ("#c71585", "mediumvioletred"),
    ("#db7093", "palevioletred"),
    ("#ff1493", "deeppink"),
    ("#ff69b4", "hotpink"),
    ("#ffb6c1", "lightpink"),
    ("#ffc0cb", "pink"),
    ("#c0c0c0", "silver"),
    ("#808080", "gray"),
    ("#a9a9a9", "darkgray"),
    ("#696969", "dimgray"),
    ("#2f4f4f", "darkslategray"),
    ("#708090", "slategray"),
    ("#778899", "lightslategray"),
    ("#d3d3d3", "lightgray"),
    ("#dcdcdc", "gainsboro"),
    ("#f5f5f5", "whitesmoke"),
    ("#800000", "maroon"),
    ("#808000", "olive"),
    ("#556b2f", "darkolivegreen"),
    ("#6b8e23", "olivedrab"),
    ("#008000", "green"),
    ("#006400", "darkgreen"),
    ("#228b22", "forestgreen"),
    ("#32cd32", "limegreen"),
    ("#90ee90", "lightgreen"),
    ("#98fb98", "palegreen"),
    ("#8fbc8f", "darkseagreen"),
    ("#3cb371", "mediumseagreen"),
    ("#2e8b57", "seagreen"),
    ("#00ff7f", "springgreen"),
    ("#adff2f", "greenyellow"),
    ("#7cfc00", "lawngreen"),
    ("#7fff00", "chartreuse"),
    ("#9acd32", "yellowgreen"),
    ("#800080", "purple"),
    ("#663399", "rebeccapurple"),
    ("#4b0082", "indigo"),
    ("#483d8b", "darkslateblue"),
    ("#6a5acd", "slateblue"),
    ("#7b68ee", "mediumslateblue"),
    ("#9370db", "mediumpurple"),
    ("#8a2be2", "blueviolet"),
    ("#9400d3", "darkviolet"),
    ("#9932cc", "darkorchid"),
    ("#ba55d3", "mediumorchid"),
    ("#da70d6", "orchid"),
    ("#ee82ee", "violet"),
    ("#dda0dd", "plum"),
    ("#d8bfd8", "thistle"),
    ("#008080", "teal"),
    ("#ffa500", "orange"),
    ("#ff8c00", "darkorange"),
    ("#ff4500", "orangered"),
    ("#ff6347", "tomato"),
    ("#ff7f50", "coral"),
    ("#f08080", "lightcoral"),
    ("#e9967a", "darksalmon"),
    ("#ffa07a", "lightsalmon"),
    ("#fa8072", "salmon"),
    ("#cd853f", "peru"),
    ("#d2691e", "chocolate"),
    ("#a0522d", "sienna"),
    ("#8b4513", "saddlebrown"),
    ("#a52a2a", "brown"),
    ("#bc8f8f", "rosybrown"),
    ("#deb887", "burlywood"),
    ("#f4a460", "sandybrown"),
    ("#d2b48c", "tan"),
    ("#f5f5dc", "beige"),
    ("#faf0e6", "linen"),
    ("#faebd7", "antiquewhite"),
    ("#ffebcd", "blanchedalmond"),
    ("#ffe4c4", "bisque"),
    ("#ffefd5", "papayawhip"),
    ("#fff8dc", "cornsilk"),
    ("#f0fff0", "honeydew"),
    ("#fffff0", "ivory"),
    ("#fffaf0", "floralwhite"),
    ("#fff5ee", "seashell"),
    ("#fdf5e6", "oldlace"),
    ("#fffafa", "snow"),
    ("#f8f8ff", "ghostwhite"),
    ("#f0f8ff", "aliceblue"),
    ("#f5fffa", "mintcream"),
    ("#ffe4e1", "mistyrose"),
    ("#fff0f5", "lavenderblush"),
    ("#ffdab9", "peachpuff"),
    ("#66cdaa", "mediumaquamarine"),
    ("#7fffd4", "aquamarine"),
    ("#00fa9a", "mediumspringgreen"),
    ("#00bfff", "deepskyblue"),
];
